config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  namespace :admin do
    get 'products/:slug/variants/:sku/move', to: 'products#move_variant', as: :move_variant
    post 'products/:slug/variants/:sku/find', to: 'products#find_product', as: :move_variant_find
    post 'products/:slug/variants/:sku/exchange', to: 'products#exchange_product', as: :move_variant_exchange
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  def move_variant
    @product = Spree::Product.find_by(slug: params[:slug])
    @variant = Spree::Variant.find_by_sku(params[:sku])
  end

  def find_product
    name = params[:name_destino]
    sku = params[:sku_destino]
    @product = nil
    if name.empty?
      if !(variant = Spree::Variant.find_by_sku(sku)).nil?
        @product = variant.product
      end
    else
      search = Spree::Product.ransack({ name_cont: name })
      @product = search.result.first
    end

    respond_to do |format|
      format.js   {}
      format.html { redirect_to request.referer }
    end
  end

  def exchange_product
    delete_old = params[:delete_old] || false
    product = Spree::Product.find(params[:product_id]) rescue nil
    if !product.nil?
      variant = Spree::Variant.find_by_sku(params[:sku])
      variant.update product_id: product.id
      if delete_old
        product_old = Spree::Product.find_by(slug: params[:slug])
        product_old.destroy! if product_old.variants.empty?
      end
      redirect_to admin_product_variants_path(product)
    else
      redirect_to admin_product_variants_path(params[:slug])
    end
  end
end

app/views/spree/admin/products/_product_table.html.erb
<tr <%== "style='color: red;'" if @product.deleted? %> id="<%= spree_dom_id @product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
  <td class="image"><%= mini_image @product %></td>
  <td><%= link_to @product.try(:name), edit_admin_product_path(@product), target: '_blank' %></td>
  <td class="text-center"><%= @product.display_price.to_html rescue '' %></td>
</tr>

app/views/spree/admin/products/find_product.js.erb
<% if @product.nil? %>
  alert('No se encontró producto con los datos ingresados');
<% else %>
  $('#destino-id').val('<%= @product.id %>');
  $('#listing_products tbody').empty();
  $('#listing_products tbody').append("<%= escape_javascript(render 'product_table') %>");
  $('.desinto').show();
<% end %>

app/views/spree/admin/products/move_variant.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render partial: 'spree/admin/shared/product_tabs', locals: {current: :variants} %>

<h1>Mover Variante</h1>
<br/>

<table class="index" >
  <colgroup>
    <col style="width: 30%" />
    <col style="width: 35%" />
    <col style="width: 35%" />
  </colgroup>
  <thead data-hook="variants_header">
    <tr>
      <th><%= Spree.t(:options) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:sku) %></th>
    </tr>
  </thead>
  <tbody>
    <tr id="<%= spree_dom_id @variant %>" <%= 'style="color:red;"' if @variant.deleted? %> data-hook="variants_row" class="<%= cycle('odd', 'even')%>">
      <td><%= @variant.options_text %></td>
      <td class="align-center"><%= @variant.display_price.to_html %></td>
      <td class="align-center"><%= @variant.sku %></td>
    </tr>
  </tbody>
</table>
<br/>

<div class="search-product">
  <h3>Buscar Producto</h3>
  <%= form_tag spree.admin_move_variant_find_path(@variant.slug, @variant.sku), method: 'post', remote: true do %>
    <%= text_field_tag :name_destino, nil, placeholder: 'Por nombre' %>
    &nbsp; O &nbsp;
    <%= text_field_tag :sku_destino, nil, placeholder: 'Por SKU' %>
    <%= submit_tag 'Buscar' %>
  <% end %>
</div>
<br><br>
<div class="desinto" style="display: none;">
  <h3>Destino</h3>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th colspan="2"><%= Spree.t(:name) %></th>
        <th class="text-center">
          <%= Spree.t(:master_price) %>
        </th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  <%= form_tag spree.admin_move_variant_exchange_path(@variant.slug, @variant.sku), method: 'post', remote: false do %>
    <%= hidden_field_tag :product_id, nil, id: 'destino-id' %>
    <%= check_box_tag :delete_old %> &nbsp;
    <%= label_tag :delete_old, "Eliminar producto original al quedar sin variantes" %>
    <%= submit_tag 'Mover', style: 'float: right;', data: { confirm: '¿Estás seguro que quieres mover la variante al producto destino?' } %>
  <% end %>
</div>